"""Weather condition and unit mapping modules."""

from omni_weather_forecast_apis.mapping.conditions import (
    OPENWEATHER_CONDITION_MAP,
    TOMORROW_IO_CONDITION_MAP,
    VISUAL_CROSSING_ICON_MAP,
    WEATHERAPI_CONDITION_MAP,
    WEATHERBIT_CONDITION_MAP,
    WMO_CODE_MAP,
    map_met_norway_condition,
    map_meteosource_condition,
    map_nws_condition,
    map_stormglass_condition,
    map_weather_unlocked_condition,
)
from omni_weather_forecast_apis.mapping.units import (
    celsius_from_fahrenheit,
    celsius_from_kelvin,
    hpa_from_inhg,
    km_from_meters,
    km_from_miles,
    mm_from_cm,
    mm_from_inches,
    ms_from_kmh,
    ms_from_knots,
    ms_from_mph,
    probability_from_percent,
    safe_convert,
)

__all__ = [
    "OPENWEATHER_CONDITION_MAP",
    "TOMORROW_IO_CONDITION_MAP",
    "VISUAL_CROSSING_ICON_MAP",
    "WEATHERAPI_CONDITION_MAP",
    "WEATHERBIT_CONDITION_MAP",
    "WMO_CODE_MAP",
    "celsius_from_fahrenheit",
    "celsius_from_kelvin",
    "hpa_from_inhg",
    "km_from_meters",
    "km_from_miles",
    "map_met_norway_condition",
    "map_meteosource_condition",
    "map_nws_condition",
    "map_stormglass_condition",
    "map_weather_unlocked_condition",
    "mm_from_cm",
    "mm_from_inches",
    "ms_from_kmh",
    "ms_from_knots",
    "ms_from_mph",
    "probability_from_percent",
    "safe_convert",
]
