"""Core type definitions for omni-weather-forecast-apis."""

from omni_weather_forecast_apis.types.config import (
    OmniWeatherConfig,
    ProviderRegistration,
    RateLimitConfig,
)
from omni_weather_forecast_apis.types.plugin import (
    PluginCapabilities,
    PluginFetchError,
    PluginFetchParams,
    PluginFetchResult,
    PluginFetchSuccess,
    PluginInstance,
    WeatherPlugin,
)
from omni_weather_forecast_apis.types.schema import (
    AlertSeverity,
    DailyDataPoint,
    ErrorCode,
    ForecastRequest,
    ForecastResponse,
    ForecastResponseRequest,
    ForecastResponseSummary,
    Granularity,
    MinutelyDataPoint,
    ModelSource,
    ProviderError,
    ProviderErrorDetail,
    ProviderId,
    ProviderResult,
    ProviderSuccess,
    SourceForecast,
    WeatherAlert,
    WeatherCondition,
    WeatherDataPoint,
)

__all__ = [
    "AlertSeverity",
    "DailyDataPoint",
    "ErrorCode",
    "ForecastRequest",
    "ForecastResponse",
    "ForecastResponseRequest",
    "ForecastResponseSummary",
    "Granularity",
    "MinutelyDataPoint",
    "ModelSource",
    "OmniWeatherConfig",
    "PluginCapabilities",
    "PluginFetchError",
    "PluginFetchParams",
    "PluginFetchResult",
    "PluginFetchSuccess",
    "PluginInstance",
    "ProviderError",
    "ProviderErrorDetail",
    "ProviderId",
    "ProviderRegistration",
    "ProviderResult",
    "ProviderSuccess",
    "RateLimitConfig",
    "SourceForecast",
    "WeatherAlert",
    "WeatherCondition",
    "WeatherDataPoint",
    "WeatherPlugin",
]
